"use client";

import { ArrowLeft, BadgeDollarSign, BarChart3, Check, Clock3, LoaderCircle, RefreshCw, Star, Users } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Summary = { users:number; trial:number; active:number; monthly:number; annual:number; lifetime:number; site_views:number; app_opens:number; plan_opens:number; checkout_starts:number; purchases:number };
type Settings = { monthly_price:number; annual_price:number; lifetime_price:number; lifetime_promo_price:number; promotion_ends_at:string };
type Feedback = { id:number; user_email:string; user_name:string; rating:number; message:string; status:string; created_at:string };
type UserRow = { id:string; email:string; subscription_status:string; plan_type:string|null; trial_ends_at:string; access_expires_at:string|null; created_at:string };
type Dashboard = { summary:Summary; settings:Settings; feedback:Feedback[]; users:UserRow[] };

function metric(label:string,value:number,icon:React.ReactNode){return <article className="app-card p-4"><span className="mb-3 grid h-10 w-10 place-items-center rounded-xl bg-[var(--brand-soft)] text-[var(--brand)]">{icon}</span><p className="text-2xl font-extrabold">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-[#74837f]">{label}</p></article>}

export function ConstructionAdminDashboard({onBack}:{onBack:()=>void}){
 const supabase=getSupabaseBrowserClient();
 const [data,setData]=useState<Dashboard|null>(null);
 const [loading,setLoading]=useState(true);
 const [message,setMessage]=useState("");
 const [settings,setSettings]=useState<Settings|null>(null);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const {data:result,error}=await supabase.rpc("admin_orcaobra_dashboard");if(error){setMessage("Não foi possível carregar o painel mestre do OrçaObra.");}else{const next=result as Dashboard;setData(next);setSettings(next.settings);}setLoading(false);},[supabase]);
 useEffect(()=>{void load();},[load]);
 const saveSettings=async()=>{if(!supabase||!settings)return;setMessage("Salvando…");const {error}=await supabase.rpc("admin_update_orcamovel_settings",{p_monthly:Number(settings.monthly_price),p_annual:Number(settings.annual_price),p_lifetime:Number(settings.lifetime_price),p_promo:Number(settings.lifetime_promo_price),p_promotion_ends_at:new Date(settings.promotion_ends_at).toISOString()});setMessage(error?"Não foi possível salvar os valores.":"Preços compartilhados atualizados.");if(!error)void load();};
 const extend=async(user:UserRow)=>{if(!supabase)return;const raw=window.prompt(`Quantos dias deseja acrescentar para ${user.email}?`,"30");if(!raw)return;const days=Number(raw);if(!Number.isInteger(days)||days<1){setMessage("Informe uma quantidade válida de dias.");return;}const {error}=await supabase.rpc("admin_extend_product_access",{p_user_id:user.id,p_product_id:"obra-civil",p_days:days});setMessage(error?"Não foi possível alterar o período.":`${days} dias acrescentados no OrçaObra para ${user.email}.`);if(!error)void load();};
 const feedbackStatus=async(id:number,status:string)=>{if(!supabase)return;const {error}=await supabase.rpc("admin_update_feedback_status",{p_id:id,p_status:status});setMessage(error?"Não foi possível atualizar a avaliação.":"Avaliação atualizada.");if(!error)void load();};
 if(loading&&!data)return <main className="grid min-h-screen place-items-center"><LoaderCircle className="animate-spin text-[var(--brand)]"/></main>;
 if(!data||!settings)return <main className="mx-auto max-w-xl p-6"><button onClick={onBack} className="quiet-button"><ArrowLeft size={18}/>Voltar</button><p className="mt-5">{message}</p></main>;
 const s=data.summary;
 return <main className="content-safe mx-auto max-w-6xl px-4 py-6 sm:px-6">
  <header className="mb-6 flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[var(--brand)]">Conta mestre</p><h1 className="text-3xl font-extrabold tracking-[-.04em]">Admin OrçaObra</h1></div><div className="flex gap-2"><button onClick={()=>void load()} className="quiet-button !px-3"><RefreshCw size={17}/></button><button onClick={onBack} className="quiet-button"><ArrowLeft size={17}/>App</button></div></header>
  {message&&<p className="mb-5 rounded-xl bg-[var(--brand-soft)] px-4 py-3 text-sm font-bold text-[var(--brand)]">{message}</p>}
  <section className="grid grid-cols-2 gap-3 md:grid-cols-5">{metric("Usuários",s.users,<Users size={19}/>)}{metric("Em teste",s.trial,<Clock3 size={19}/>)}{metric("Planos ativos",s.active,<Check size={19}/>)}{metric("Compras",s.purchases,<BadgeDollarSign size={19}/>)}{metric("Avaliações",data.feedback.length,<Star size={19}/>)}</section>
  <section className="mt-6 app-card p-5"><h2 className="text-xl font-extrabold">Funil comercial</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{metric("Visitas ao site",s.site_views,<BarChart3 size={18}/>)}{metric("Entradas no app",s.app_opens,<BarChart3 size={18}/>)}{metric("Abriram planos",s.plan_opens,<BarChart3 size={18}/>)}{metric("Iniciaram compra",s.checkout_starts,<BarChart3 size={18}/>)}{metric("Compraram",s.purchases,<BarChart3 size={18}/>)}</div></section>
  <section className="mt-6 app-card p-5"><h2 className="text-xl font-extrabold">Preços e promoção</h2><p className="mt-1 text-sm text-[#74837f]">Por decisão atual, estes valores são os mesmos do OrçaMóvel.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{([["monthly_price","Mensal"],["annual_price","Anual"],["lifetime_price","Vitalício"],["lifetime_promo_price","Vitalício promocional"]] as const).map(([key,label])=><label key={key}><span className="field-label">{label}</span><input className="field-input" type="number" min="0" step=".01" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}<label><span className="field-label">Fim da promoção</span><input className="field-input" type="datetime-local" value={settings.promotion_ends_at.slice(0,16)} onChange={e=>setSettings({...settings,promotion_ends_at:e.target.value})}/></label></div><button onClick={()=>void saveSettings()} className="primary-button mt-4">Salvar condições</button></section>
  <section className="mt-6 app-card overflow-hidden"><div className="p-5"><h2 className="text-xl font-extrabold">Avaliações recebidas</h2></div><div className="divide-y divide-[#e4ece9]">{data.feedback.length?data.feedback.map(f=><article key={f.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-extrabold">{f.user_name||f.user_email}</p><p className="text-xs text-[#74837f]">{f.user_email} · {new Date(f.created_at).toLocaleDateString("pt-BR")}</p></div><span className="font-bold text-[#a77826]">{"★".repeat(f.rating)}{"☆".repeat(5-f.rating)}</span></div><p className="mt-3 text-sm leading-6">{f.message}</p><div className="mt-3 flex gap-2"><button onClick={()=>void feedbackStatus(f.id,"approved")} className="secondary-button !min-h-9 !px-3">Aprovar para o site</button><button onClick={()=>void feedbackStatus(f.id,"archived")} className="quiet-button !min-h-9 !px-3">Arquivar</button></div></article>):<p className="p-5 text-sm text-[#74837f]">Nenhuma avaliação do OrçaObra ainda.</p>}</div></section>
  <section className="mt-6 app-card overflow-hidden"><div className="p-5"><h2 className="text-xl font-extrabold">Usuários e planos</h2><p className="mt-1 text-sm text-[#74837f]">Mensal: {s.monthly} · Anual: {s.annual} · Vitalício: {s.lifetime}</p></div><div className="divide-y divide-[#e4ece9]">{data.users.map(u=><article key={u.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-bold">{u.email}</p><p className="text-xs text-[#74837f]">{u.subscription_status==="trial"?"Teste":u.subscription_status} · {u.plan_type||"Sem plano"} · entrou em {new Date(u.created_at).toLocaleDateString("pt-BR")}</p></div><button onClick={()=>void extend(u)} className="secondary-button !min-h-10 !px-3"><Clock3 size={16}/>Dar mais dias</button></article>)}</div></section>
 </main>;
}
